# This is a basic workflow to help you get started with Actions

name: Build

on:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
  # Pushes to master (or main when it is renamed)
  push:
    branches:
      - main
      - master
  # Pull requests to master (or main when it is renamed)
  pull_request:
    branches:
      - main
      - master

jobs:
  # Install Ubuntu dependencies for parmetis, metis, petsc, sqlite and HDF5
  build:
    runs-on: ubuntu-latest
    env:
      COMPILER: gnu
      HDF5_INSTALL_PATH: /usr/lib/x86_64-linux-gnu/hdf5/openmpi/
      METIS_INSTALL_PATH: /usr/lib/x86_64-linux-gnu
      PARMETIS_INSTALL_PATH: /usr/lib
      PETSC_INSTALL_PATH: /usr/lib/x86_64-linux-gnu
      SQLITE_INSTALL_PATH: /usr/lib/x86_64-linux-gnu
      TREETIMER_PATH: /home/runner/work/CUP-CFD/CUP-CFD/treetimer
      PETSC_INCLUDE_DIR: /usr/include/petsc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Update apt
      - name: apt-get update
        run: >-
          sudo apt-get update && sudo apt-get install -yq
          libparmetis-dev libparmetis4.0
          libmetis-dev libmetis5 metis
          petsc-dev 
          libsqlite3-dev sqlite3
          libhdf5-mpi-dev libhdf5-dev

      - name: Checkout TreeTimer
        run: cd $GITHUB_WORKSPACE && git clone https://github.com/warwick-hpsc/treetimer.git

      - name: Build TreeTimer
        run: cd $GITHUB_WORKSPACE/treetimer && make all
        env:
          COMPILER: gnu
          SQLITE_DIR: /usr/include

      - name: Build CUP-CFD Debug 
        run: cd $GITHUB_WORKSPACE && sh +x compile.sh
        