# This is a basic workflow to help you get started with Actions

name: InstallAndCacheDependencies

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-deps:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Update apt
      - name: apt-get update
        run: sudo apt-get update

      # Install Parmetis
      - name: Install Parmetis
        run: sudo apt-get install -yq libparmetis-dev libparmetis4.0
      
      # Install Metis
      - name: Install Metis
        run: sudo apt-get install -yq libmetis-dev libmetis5 metis
        
      # Install PETSc
      - name: Install PETSc
        run:  sudo apt-get install -yq libpetsc64-complex3.14 libpetsc64-complex3.14-dbg libpetsc64-complex3.14-dev

      # Install SQLite3
      - name: Install SQLite3
        run: sudo apt-get install -yq libsqlite3-0 libsqlite3-0-dbgsym libsqlite3-dev sqlite3
        
      # Install HDF5
      - name: Install HDF5
        run: sudo apt-get install -yq libhdf5-mpi-dev
